atom/teletype

- lib/buffer-binding.js
- package.json
- test/teletype-package.test.js
Fixes #189
This was an oversight when implementing `HistoryProvider` APIs: we added this method to teletype-crdt but forgot to add it to `BufferProxy` (in teletype-client) and `BufferBinding` (in this package).
I have tested that this fixes the above issue with vim-mode-plus.
> Add support for `getChangesSinceCheckpoint` API

- lib/join-portal-component.js
- test/portal-list-component.test.js
* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions.
Trims any whitespace off of a potential portal ID.  The automatic clipboard reading is super cool :).
None.
Better portal ID validation.
None?
Fixes #197.
> Trim whitespace from portal ID

- test/portal-list-component.test.js
The changes in https://github.com/atom/teletype/pull/198 duplicated the test for how we handle the scenario where the clipboard contains content that is _not_ a portal ID:
https://github.com/atom/teletype/blob/5a4a7d473265396c14ad9a0ce435b3529040fb13/test/portal-list-component.test.js#L180-L184
Those assertions ☝️ existed prior to #198, and #198 duplicates those existing assertions:
https://github.com/atom/teletype/blob/5a4a7d473265396c14ad9a0ce435b3529040fb13/test/portal-list-component.test.js#L197-L201
This PR removes that duplication. 
---
Also, prior to #198, we had a single `test` function that covered all scenarios related to fetching the portal ID from the clipboard. #198 added a second `test` function specifically related to the scenario where the clipboard contains a portal ID …
> Streamline tests related to fetching portal ID from clipboard

- index.js
- lib/teletype-package.js
- package.json
Closes #204
Fixes #202
This incorporates the changes from @icetee in #204 and updates teletype-client to support the new `pusherOptions` parameter (see https://github.com/atom/teletype-client/pull/37).
> Fix pusher warnings

- lib/package-initialization-error-component.js
- lib/popover-component.js
- lib/portal-status-bar-indicator.js
- lib/teletype-package.js
- styles/teletype.less
- test/teletype-package.test.js
Fixes #210 
Previously, we would only show a notification when failing to initialize the client (e.g. this could happen when an error occurs while checking the protocol version) without informing the popover. This was also causing exceptions like #210, because we were failing to instantiate objects like `PortalBindingManager` due to the initialization error.
With this pull-request we will:
* Show an error message in the popover too, coloring the status bar indicator as red when that happens.
* Don't attempt to re-initialize the client if it is outdated or an error has previously occurred.
<p align=center>
</p>
I have tested this works correctly with a few themes (One Light UI, One Dark UI, Atom Material, Nord UI) by opening the DevTools and enabling the `Offline` checkbox in the Network …
> Show initialization failures also in the popover

- lib/portal-status-bar-indicator.js
- lib/teletype-package.js
- test/teletype-package.test.js
* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions.
On package deactivation, remove any added commands and the status bar tile, if present.  There was an existing `dispose` method, but that never gets called.  The proper name is `deactivate`.
Test plan:
* Disable teletype
* Try searching for `teletype` commands (expected: none to exist)
* Status bar tile should not be visible
* Re-enable teletype
* Try searching for `teletype` commands (expected: commands exist)
* Status bar tile should be visible
None.
Proper package deactivation.
None.
Fixes #199
> Dispose of status bar and commands when deactivating

- lib/join-portal-component.js
- test/portal-list-component.test.js
* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions.
When attempting to join a new session, the join button did no validation on the specified portal id. This change now disables the join button in the following scenarios:
1. When the portal id is blank
2. When the portal id is not a valid UUID
Once the value has been validated, the button becomes enabled and allows the user to click it.
Originally I considered just showing an error message when the button was clicked, but this felt sloppy since this is more of a input validation step. Using this method, the button prevents the attempt all together unless …
> Disable join button if portal ID is invalid.

- lib/authentication-provider.js
- lib/portal-status-bar-indicator.js
- lib/teletype-package.js
- test/teletype-package.test.js
Closes #194 
This pull-request introduces a new `Sign out` command that allows users to sign out from Teletype (note how the user stays signed out even after reloading Atom):
<p align="center"><img src="https://user-images.githubusercontent.com/482957/33021430-22864c06-ce02-11e7-9ae8-e1530db856f8.gif"/></p>
Considering how infrequent this action is, I think we can avoid providing a graphical affordance for it in the popover and just have a simple command. Such command will be shown to users only when they have effectively signed in.
/cc: @nathansobo @jasonrudolph
> Allow users to sign out via `Teletype: Sign out` command

- lib/guest-portal-binding.js
This pull request refactors `GuestPortalBinding.setActiveEditorProxy(editorProxy)` into a [Composed Method](http://don.fed.wiki.org/view/composed-method) (i.e., such that all operations in the method are at the same level of abstraction).
> Refactor `GuestPortalBinding.setActiveEditorProxy(editorProxy)`

- .travis.yml
- index.js
- lib/buffer-binding.js
- lib/editor-binding.js
- lib/guest-portal-binding.js
- lib/popover-component.js
- lib/portal-binding-manager.js
- package.json
- test/editor-binding.test.js
- test/portal-list-component.test.js
- test/teletype-package.test.js
Configure linter for [JavaScript Standard Style](https://standardjs.com) to foster consistency with the [Atom style guide](https://github.com/atom/atom/blob/572aec74d9fb612849a2b02cb5e54d515341c0fd/CONTRIBUTING.md#javascript-styleguide).
> 👕  Set up Standard JS linter

- doc/rfcs/001-allow-guests-to-open-multiple-remote-buffers.md
- lib/buffer-binding.js
- lib/editor-binding.js
- lib/guest-portal-binding.js
- lib/host-portal-binding.js
- lib/portal-binding-manager.js
- lib/site-positions-component.js
- lib/site-positions-controller.js
- lib/teletype-package.js
- package.json
- styles/teletype.less
- test/buffer-binding.test.js
- test/editor-binding.test.js
- test/guest-portal-binding.test.js
- test/helpers/editor-helpers.js
- test/helpers/fake-editor-proxy.js
- test/helpers/fake-portal.js
- test/helpers/ui-helpers.js
- test/host-portal-binding.test.js
- test/portal-binding-manager.test.js
- test/portal-list-component.test.js
- test/site-positions-controller.test.js
- test/teletype-package.test.js
This pull request implements the core parts of the functionality described in [RFC-001](https://github.com/atom/teletype/blob/1380adb2725f3c70b27e096d84cd9af7bd2819be/doc/rfcs/001-allow-guests-to-open-multiple-remote-buffers.md):
> If you continue to follow the host [after first joining the portal], any time they switch to a new buffer, a new editor for that remote buffer is automatically added to your workspace and focused. Existing editors for previous remote buffers are not automatically closed when this switch occurs.
>
> When a host closes a buffer, it will be removed from all guest portals. ...
>
> You can follow any other guest participating in the host's workspace in the exact same way. If they move between buffers, you will follow them.
The following features of RFC-001 will be …
> Allow guests to collaborate on multiple remote buffers (Part 1)

- lib/package-outdated-component.js
- test/teletype-package.test.js
Closes #269 
This pull request redirects the user to the Settings View update panel instead of showing the package's settings page. The previous behavior was confusing and not very useful as pointed out in the linked issue.
@jasonrudolph @ungb: what do you think?
> Show updates panel when there is a breaking protocol change

- lib/buffer-binding.js
- lib/editor-binding.js
- lib/guest-portal-binding.js
- lib/host-portal-binding.js
- test/buffer-binding.test.js
- test/editor-binding.test.js
- test/site-positions-controller.test.js
In #270, 3a30144db33bf2858f347a4e112e59228cc030e6 duplicates the logic for determining the prefix for a remote title/path.
https://github.com/atom/teletype/blob/3a30144db33bf2858f347a4e112e59228cc030e6/lib/buffer-binding.js#L48-L49
https://github.com/atom/teletype/blob/3a30144db33bf2858f347a4e112e59228cc030e6/lib/editor-binding.js#L65-L66
This pull request proposes a refactoring that eliminates that duplication and removes the dependency on `Portal` in `EditorBinding` and `BufferBinding`.
@as-cii: What do you think?
> Remove duplicate logic for calculating remote prefix

- lib/buffer-binding.js
- lib/editor-binding.js
- test/buffer-binding.test.js
- test/editor-binding.test.js
Closes https://github.com/atom/teletype/issues/240
This pull request uses the APIs introduced in https://github.com/atom/teletype-client/pull/45 to:
* Perform a save request when attempting to save a remote buffer on the guest (e5aa4c0).
* Honor the save request on the host by flushing changes to disk. Requests to save in-memory buffers are ignored by the host. (0edbe49)
* Open a new Atom instance and share a portal.
* Open a new Atom instance and join the previously shared portal.
* Edit the buffer on the guest portal and save.
* Observe saves being relayed to the host buffer.
/cc: @nathansobo @jasonrudolph
> Save buffer on the host when attempting to save it on the guest

- lib/portal-binding-manager.js
Previously, deactivating the TeletypePackage would only dispose the bindings without tearing down the associated portal instances. This would cause the disposed bindings to keep receiving messages from e.g. Portal or EditorProxy and would throw errors because the binding methods were called while being in a inconsistent/disposed state.
This pull request addresses the exceptions we were observing in the DevTools when running tests locally by closing/leaving all the portals managed by PortalBindingManager when tearing down the package.
/cc: @jasonrudolph
> Close/leave portals when deactivating TeletypePackage

- lib/guest-portal-binding.js
- lib/host-portal-binding.js
- lib/site-positions-controller.js
- test/site-positions-controller.test.js
Fixes #276
Previously, we would show site position avatars on the right hand side of the workspace center element. As illustrated in the aforementioned issue, this could cause a confusing behavior when interacting with split panes:
With this pull request we are moving site position avatars from the "workspace center" element to the currently active remote pane item:
| before  | after   |
|---------|---------|
| ![before](https://user-images.githubusercontent.com/482957/33987517-6ead8668-e0c1-11e7-902a-ce374c63ef61.gif) | ![after](https://user-images.githubusercontent.com/482957/33987519-70c29f6a-e0c1-11e7-9b6c-e1b99bd5ab90.gif) |
On a portal with one or more guests:
* Create some split items on the host (or, analogously, move remote buffers into other panes on the guest).
* Move among …
> Show site position avatars inside remote pane items

- doc/rfcs/001-allow-guests-to-open-multiple-remote-buffers.md
RFC-001 currently includes the following paragraph:
> When a host closes a buffer, it will be removed from all guest portals. If another participant is working in that same buffer (i.e., not following the host), Teletype will first ask the host to confirm their intention to remove the buffer from the portal.
This pull request proposes that we remove the second sentence from that paragraph.
Our motivation for this change is as follows:
- If a host attempts to close a buffer that the guest is editing, Atom will detect that the buffer has unsaved changes, and Atom will automatically prompt the host to confirm their intention to close the buffer. If Teletype *also* attempts to confirm the host's intention to close the buffer, we'll essentially be prompting the host _twice_ before they can …
> Update RFC-001 to remove extraneous step

- index.js
- lib/package-initialization-error-component.js
- lib/popover-component.js
- lib/teletype-package.js
- styles/teletype.less
The initialization errors seen in #250 appear to be transient. https://github.com/atom/teletype/issues/250#issuecomment-348382047 notes:
> On OSX I had `Failed to load resource: net::ERR_NAME_NOT_RESOLVED` but was also unable to check for outdated packages in atom. It may be a DNS race, where it times out before resolving. Loading https://atom.io in a browser and a restart "fixed" it for the time being. Making me think that it's an infrastructure or network error rather than `teletype` specific.
Since "trying again" often Atom seems to resolve the issue, this pull request provides a "Reload Atom" button when the popover component displays an initialization error.
1. Disable network access on computer
2. Open Atom window
3. Verify that "Reload Atom" button appears in Teletype popover
4. …
> Provide "reload" button when displaying initialization error

- doc/rfcs/000-template.md
Building on the RFC experiment initiated in https://github.com/atom/teletype/pull/231, this pull request adds a template for use in contributing new RFCs.
Much like https://github.com/atom/teletype/pull/231, this pull request borrows heavily from the [approach used by the Rust community](https://github.com/rust-lang/rfcs/blob/b38be1133a36f060208a13d2c0e291a0a7b90d99/0000-template.md).
As we continue the RFC experiment, we'll likely follow up with some documentation in our contribution guide to help community members create RFCs. In the meantime, this template feels useful to add now, so that we can provide a starting point for potential contributors (e.g., https://github.com/atom/teletype/issues/30#issuecomment-348055825 and https://github.com/atom/teletype/issues/281#issuecomment-35154997 …
> Add RFC template

- lib/buffer-binding.js
- package.json
- test/buffer-binding.test.js
- test/helpers/fake-portal.js
- test/host-portal-binding.test.js
🍐 d with @as-cii 
Closes #300 
Atom 1.25 introduces two big changes that affect the Teletype package.
1. [x] It upgrades to a version of `text-buffer` containing the changes in https://github.com/atom/text-buffer/pull/282, which changes the behavior `undo: "skip"` option when calling `setTextInRange`. The change is now pushed to the history provider to avoid corruption of the default linear history. In addition, we expect the history provider to implement the `groupLastChanges()` method, which groups the last change with the change before it. This PR updates Teletype to no longer assume `undo: "skip"` does not push the change to the history and implements the new method.
2. [x] We upgrade to Electron 1.17. This seems to introduce some changes in the underlying WebRTC implementation that …
> Update for compatibility with Atom 1.25

- .travis.yml
In addition to running CI against the latest stable and beta versions of Atom, also run CI against atom/atom's master branch. This will help us more quickly identify issues like #300, in which a change on atom/atom's master branch breaks Teletype.
/xref atom/ci#80
> Add Atom dev channel to build matrix

- .travis.yml
In https://github.com/atom/teletype/pull/302#discussion_r161645497, @Arcanemagus suggested an improvement to the `script` section in `.travis.yml`:
> Note that piping a script like this can lead to issues if the connection gets killed in the middle of the script executing and it can be _very_ hard to diagnose as the script output gets quite garbled. That's why `atom/ci` recommends [this way](https://github.com/atom/ci/blob/83744c0308ea7188ff90bd719a86b9dc0fb1d0d0/.travis.yml#L18-L21).
This pull request adopts `atom/ci`'s recommended approach.
---
@Arcanemagus: Thanks for the tip! ⚡️
> Use atom/ci's recommended commands for fetching & running the build script

- CHANGELOG.md
Closes #303
---
Following up on the feedback in #303, I've added [release notes for Teletype's last four releases](https://github.com/atom/teletype/releases), and we hope to offer release notes each time we  publish a new release going forward.
To help people discover the release notes, this pull request adds a `CHANGELOG.md` file (based on the feed back in https://github.com/atom/teletype/issues/303#issuecomment-358111953) that links to the Releases page (https://github.com/atom/teletype/releases).
> Add CHANGELOG.md linking to Releases page

- index.js
Stats are currently effectively disabled by the Chrome content security policy but we should [explicitly disable them](https://github.com/pusher/pusher-js/tree/v4.1.0#disablestats-boolean) to get rid of the console log warning and to prevent them accidentally becoming enabled should the CSP or implementation change.
If somebody does want to enable them we would need to:
1. Honor the `telemetryConsent` config setting in Atom - would need to be set to `limited` for opt-in
2. Need to modify the CSP to enable this host to get through Chrome
> Force stats collection to be disabled

- index.js
- lib/package-initialization-error-component.js
- lib/popover-component.js
- lib/teletype-package.js
- package.json
- test/teletype-package.test.js
To aid in diagnosing and debugging package initialization errors (https://github.com/atom/teletype/issues/266), this pull request incorporates the changes from atom/teletype-client#50 to provide a pre-filled GitHub Issue body with useful diagnostic information. 
For example, clicking on the `atom/teletype` link in the popover...
...will prefill an issue like this:
---
🍐'd with @as-cii
> Improve diagnostics for package initialization errors

- lib/editor-binding.js
- lib/guest-portal-binding.js
- test/editor-binding.test.js
- test/teletype-package.test.js
This change addresses the following item from the task list in https://github.com/atom/teletype/issues/268:
> - [x] Close remote buffers on guest when portal gets closed or disconnected (https://github.com/atom/teletype/commit/9d9f74c11a33e81beca11d5cf16ac4725f1e2d5b#commitcomment-26310833)
In the discussion in https://github.com/atom/teletype/commit/9d9f74c11a33e81beca11d5cf16ac4725f1e2d5b#commitcomment-26310833, we observed that it's often "annoying that the host's buffers persist as unsaved files after they close their portal. With one editor, it was fine, but now there are quite a few tabs to clean up after a host terminates their session." With the changes in this pull request, when the host closes the portal, Teletype will clean up the guest's workspace to remove the closed portal's …
> Close remote buffers on guest when host closes portal

- lib/editor-binding.js
- test/teletype-package.test.js
Prior to #319, when the host closed the portal, Teletype would transform the remote editors in the guest's workspace into local untitled/unsaved editors. As of #319, when the host closed the portal, Teletype *closes* remote editors in the guest's workspace. As a result, we no longer need the logic for transforming the remote editors into local editors.
> 🔥 Remove obsolete logic for "deremotifying" guest editors

- lib/editor-binding.js
- test/editor-binding.test.js
This is a workaround to a [bug that exists in Atom core](https://github.com/atom/text-buffer/pull/210) where, if a marker is destroyed during the handling of an `onDidCreateMarker` event, subsequent observers are still notified of the creation event, even though the marker is already destroyed.
This happens frequently when two selections overlap, whereby Atom merges the selections, destroying the most recent one inside of an `onDidCreateMarker` event handler. This should likely be fixed in Atom core (i.e., when iterating over observers to notify them of marker creation, if any observer causes the marker to be destroyed, don't notify the remaining observers).
In the meantime, this feels like a reasonable workaround for Teletype, and will prevent participants from seeing spurious cursors …
> Don't relay selections that are destroyed when creation event is emitted

- LICENSE.md
* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions.
Updated the LICENSE.md file from
```
Copyright (c) 2017 GitHub
```
to
```
Copyright (c) 2017-2018 GitHub Inc.
```
Used this for reference
LICENSE.md file of atom's repo: https://github.com/atom/atom/blob/master/LICENSE.md
None
Correct license year in LICENSE.md
None
Checked the LICENSE.md file to display the right year
Fixes #330
> Updated license year in LICENSE.md file

- lib/editor-binding.js
- lib/get-editor-uri.js
- lib/guest-portal-binding.js
- lib/is-uuid.js
- lib/join-portal-component.js
- lib/portal-binding-manager.js
- lib/portal-id-helpers.js
- lib/teletype-package.js
- lib/uri-helpers.js
- package.json
- test/teletype-package.test.js
This pull request implements the following item from the task list in https://github.com/atom/teletype/issues/109:
> - [ ] Teach Teletype to join portal via URL
>     - Add URI handler
>     - Add command for getting the URL
>     - Automatically join the portal when URL is followed (for now)
>     - Don't provide any UI for getting the URL (for now)
This is the first in a series of pull requests that will implement the various aspects described in https://github.com/atom/teletype/issues/109. Once all items in that task list have been addressed, we'll publish a new Teletype release with support for joining a portal via a URL.
- `atom://teletype/portal/42`
- `atom://teletype/whoops`
- `atom://teletype/`
- `atom://teletype`
#109 
#344
> Join portal via URL (Part 1)

- lib/guest-portal-binding.js
- lib/host-portal-binding-component.js
- lib/host-portal-binding.js
- lib/join-portal-component.js
- lib/portal-binding-manager.js
- lib/portal-id-helpers.js
- lib/teletype-package.js
- styles/teletype.less
- test/portal-list-component.test.js
- test/teletype-package.test.js
This pull request is a follow-up to #346 and changes the UI to accept and show portal URIs instead of just their IDs. This has the advantage of uniforming the ways a portal can be shared and joined. For backward compatibility, we will still accept and parse portal IDs. The following are a few highlights of the proposed UI changes:
<p align="center">
</p>
This new code does not really validate that the supplied URL has the right prefix (i.e., starts with `atom://teletype/portal/`), but literally just attempts to extract a UUID from a string. One downside of this is that users may accidentally paste a URL belonging to a different website/service. We think this is okay because the odds of it happening are relatively low and, even if it happens sometimes, it will be a non-destructive action. …
> Join portal via URL (Part 2)

- styles/teletype.less
This PR tries to fix #345 by adding more `z-index`es.
Use a separate element for the background.
Icon is not hidden
None
Closes #345
> Fix stacking of link icon

- index.js
- lib/host-portal-binding-component.js
- lib/join-via-external-app-dialog.js
- lib/teletype-package.js
- package.json
- styles/dialogs.less
- styles/teletype.less
- test/helpers/atom-environments.js
- test/teletype-package.test.js
Closes #109.
Building on the work in #346 and #348, this pull request implements the final item from the task list in https://github.com/atom/teletype/issues/109:
> - [ ] Ask the user to confirm before joining the portal [[motivation](https://github.com/atom/teletype/blob/e35483b1fa69c3ef1ef56f0c437000d4dcda934b/doc/rfcs/003-quickly-collaborate-with-coworkers-and-friends.md#join-a-portal-via-url)]
> Join portal via URL (Part 3 of 3)

- lib/teletype-service.js
- test/teletype-service.test.js
https://github.com/atom/fuzzy-finder/pull/343 taught the fuzzy-finder package to gracefully handle the situation where the Teletype service is unable to fetch the list of remote editors. But instead of requiring all consumers of the service to deal with this scenario, this pull request updates the service to return an empty array (instead of `null`) if the Teletype service is unable to fetch the list of remote editors.
> Return empty list of editors if PortalBinderManager is unavailable

- styles/teletype.less
This turns off pointer events on `SitePositionsComponent` and enables them again on each avatar.
User can click through to lines underneath.
None
1. Clicking on lines next to the avatars is possible.
2. Clicking on avatars is possible.
Fixes #362
> Fix clicking on lines next to the avatars

- lib/site-positions-component.js
- package.json
- styles/teletype.less
- test/site-positions-component.test.js
Closes #338
Depends on https://github.com/atom/teletype-client/pull/61
---
This pull request implements the design shown in https://github.com/atom/teletype/issues/338#issuecomment-371802426.
In the screenshot below, we see the addition of colored borders around some avatars. When a participant's cursor appears in the current editor, the avatar will now have a border with a color that matches the user's cursor color.
> Add border around avatar to identify their cursor color

- .travis.yml
Refs https://github.com/atom/ci/issues/93
We recently [switched from Travis to Azure Pipelines for our Atom Linux artifacts](https://github.com/atom/atom/pull/19597), and as an unexpected consequence, package builds that rely on Atom started failing with the following error installing the Atom package:
```
Downloading latest Atom release on the dev channel...
dpkg-deb: error: archive 'atom-amd64.deb' has premature member 'control.tar.xz' before 'control.tar.gz', giving up
```
On Travis, we were building Atom on Ubuntu 14. On Azure Pipelines, we're using Ubuntu 16, and it seems that packages built on Ubuntu 16 trigger this error on Ubuntu 14, which is the version currently used on our package builds as well. Seeing as how Ubuntu 14 has reached "end of standard support", I think it makes …
> Fix tests that run against Atom dev channel by upgrading to Ubuntu 16
